name: "Run Gradle Tests"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Run tests
        uses: gradle/gradle-build-action@v2
      - name: Change gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew test
