name: "Validate Gradle Wrapper"
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Run tests
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew test
